CREATE TABLE `book` (
  `ISBN` CHAR(13) NOT NULL,
  `bookname` VARCHAR(30) NOT NULL,
  `author` VARCHAR(20) NOT NULL,
  `press` VARCHAR(20) NOT NULL,
  `price` FLOAT NOT NULL,
  `isborrow` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ISBN`)
) ENGINE=INNODB DEFAULT CHARSET=utf8


CREATE TABLE `user` (
  `uid` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `gender` VARCHAR(10) DEFAULT NULL,
  `borrowNum` INT(10) UNSIGNED NOT NULL,
  `psd` VARCHAR(20) NOT NULL,
  `level` INT(11) NOT NULL,
  PRIMARY KEY (`uid`)
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8


CREATE TABLE `borrowbook` (
  `bid` INT(11) NOT NULL AUTO_INCREMENT,
  `uid` INT(11) NOT NULL,
  `ISBN` CHAR(13) NOT NULL,
  `btime` DATE NOT NULL,
  `srtime` DATE NOT NULL,
  `isbor` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`bid`),
  KEY `fk1` (`uid`),
  KEY `fk2` (`ISBN`),
  CONSTRAINT `fk1` FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk2` FOREIGN KEY (`ISBN`) REFERENCES `book` (`ISBN`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8


CREATE TABLE `returnbook` (
  `rid` INT(11) NOT NULL AUTO_INCREMENT,
  `bid` INT(11) NOT NULL,
  `rtime` DATE DEFAULT NULL,
  PRIMARY KEY (`rid`),
  KEY `fk3` (`bid`),
  CONSTRAINT `fk3` FOREIGN KEY (`bid`) REFERENCES `borrowbook` (`bid`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8

